# Generated by Django 6.0.2 on 2026-02-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometers', models.IntegerField()),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=10)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi Automatic', 'Semi Automatic')], max_length=30)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['brand'], name='myapp_vehic_brand_b60b48_idx'), models.Index(fields=['fuel'], name='myapp_vehic_fuel_d3ba05_idx'), models.Index(fields=['status'], name='myapp_vehic_status_d85489_idx'), models.Index(fields=['price'], name='myapp_vehic_price_9bc372_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.vehicle')),
            ],
        ),
    ]
