# Generated by Django 6.0.2 on 2026-02-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_featured'], name='myapp_vehic_is_feat_9f6b73_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(condition=models.Q(('status', 'Available')), fields=['status'], name='available_only_idx'),
        ),
    ]
