# Generated by Django 6.0.2 on 2026-03-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_postgres_fuzzy_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'is_featured'], name='status_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'fuel'], name='status_fuel_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'transmission'], name='status_transmission_idx'),
        ),
    ]
